repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
      - id: lint
        name: flake8
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
